tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "withgraphite/tap"

brew "mas"
brew "zoxide"
brew "asdf"
brew "jq"
brew "yq"
brew "yj"
brew "yj"
brew "rg"
brew "fd"
brew "bat"
brew "starship"
brew "curl"
brew "wget"
brew "tealdeer"
brew "coreutils"
brew "gnu-sed"
brew "gnu-tar"
brew "pcre"
brew "moreutils"
brew "graphite"

cask "font-fira-code-nerd-font"
cask "iterm2"
cask "grid"
cask "intellidock"
cask "komet"
cask "1password"
cask "visual-studio-code"
cask "jetbrains-toolbox"
cask "setapp"
cask "logi-options-plus"

mas "Refined GitHub", id: 1519867270
mas "AdGuard for Safari", id: 1440147259
mas "StopTheMadness", id: 1376402589
mas "1Password for Safari", id: 1569813296
mas "Hush", id: 1544743900
